let categories = {
    // 'Action/Adventure': 32,
    // 'Anime/Animation': 31,
    // 'Autos & Vehicles': 2,
    // 'Classics': 33,
    'Comedy': 23,
    // 'Documentary': 35,
    // 'Drama': 36,
    // 'Education': 27,
    'Entertainment': 24,
    // 'Family': 37,
    'Film & Animation': 1,
    // 'Foreign': 38,
    'Gaming': 20,
    // 'Horror': 39,
    'How to & Style': 26,
    // 'Movies': 30,
    'Music': 10,
    // 'News & Politics': 25,
    // 'Nonprofits & Activism': 29,
    // 'People & Blogs': 22,
    'Pets & Animals': 15,
    // 'Sci-Fi/Fantasy': 40,
    'Science & Technology': 28,
    // 'Short Movies': 18,
    // 'Shorts': 42,
    // 'Shows': 43,
    'Sports': 17,
    // 'Thriller': 41,
    // 'Trailers': 44,
    // 'Travel & Events': 19,
    // 'Videoblogging': 21,
};

export default categories;
